name: zm-deals

services:
  postgres:
    image: postgres:17.0
    container_name: zm-deals-postgres
    hostname: ${DB_HOST}
    ports:
      - "5432:${DB_PORT}"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    container_name: zm-deals-redis
    ports:
      - "6379:${REDIS_PORT:-6379}"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:2.70
    container_name: zm-deals-redisinsight
    ports:
      - "5540:5540"
 
    restart: unless-stopped
    depends_on:
      - redis

volumes:
  redis-data:
  pg-data:
